export const services = [
  "Legal Consultation Services",
  "Foreign Investment Services",
  "Contracts",
  "Notarization",
  "Insurance",
  "… and Defense in All Cases",
  "Banks and Financial Institutions",
  "Corporate Governance Services",
  "Companies Liquidation",
  "Internal Regulations for Companies",
  "Services for Companies and Institutions",
  "Arbitration",
  "Intellectual Property",
  "Corporate Restructuring and Reorganization",
  "Establishing National and Foreign Companies",
  "Commercial Agencies",
  "Supporting Vision 2030",
  "Estates",
  "Team Service",
];
